name: tr187_gamelove
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  injectable: ^2.3.2
  lottie: ^3.1.3
  flash_card: ^0.1.0

  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  preload_page_view: ^0.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  flutter_svg: ^2.0.9

  firebase_remote_config: ^5.0.4
  firebase_crashlytics: ^4.0.4
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_messaging: ^15.0.4
  app_tracking_transparency: ^2.0.6
  appsflyer_sdk: ^6.15.1

  google_fonts: ^6.2.1
  package_info_plus: ^8.0.2
  share_plus: ^10.0.2
  flutter_easyloading: ^3.0.5
  device_info_plus: ^11.1.0
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/anim/
    - assets/sound/
    - assets/data/

